# Generated by Django 5.1.4 on 2025-01-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0003_book_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
