# Generated by Django 5.1.4 on 2025-01-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0004_remove_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('FIC', 'Fiction'), ('NF', 'Non-Fiction'), ('SCI', 'Science'), ('ART', 'Art'), ('BIO', 'Biography'), ('KID', 'Kids')], default='NF', max_length=3),
        ),
    ]
