# Generated by Django 5.1.4 on 2025-01-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0008_category_description_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(null=True, upload_to='books/', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='books/img/default.jpg', upload_to='books/img', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='categories/img'),
        ),
    ]
