# Generated by Django 5.1.4 on 2025-01-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0009_alter_book_file_alter_book_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(null=True, upload_to='books/files', verbose_name='فایل'),
        ),
    ]
