# Generated by Django 5.1.4 on 2025-01-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0011_alter_book_file_alter_book_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(default='C:\\Users\\Rojiar\\Desktop\\BookProject\\media/file/books/book.pdf', upload_to='C:\\Users\\Rojiar\\Desktop\\BookProject\\media/file/books', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='C:\\Users\\Rojiar\\Desktop\\BookProject\\media/img/books/default.jpg', upload_to='C:\\Users\\Rojiar\\Desktop\\BookProject\\media/img/books', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='C:/img/categories'),
        ),
    ]
