# Generated by Django 5.1.4 on 2025-01-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0013_alter_book_file_alter_book_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(default='file/books/book.pdf', upload_to='file/books', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='img/books/default.jpg', upload_to='img/books', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='img/categories'),
        ),
    ]
