# Generated by Django 5.1.4 on 2025-01-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0014_alter_book_file_alter_book_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(default='assets/file/book.pdf', upload_to='file/books', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='assets/img/default.jpg', upload_to='img/books', verbose_name='تصویر'),
        ),
    ]
