# Generated by Django 5.1.4 on 2025-01-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0015_alter_book_file_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sell',
            field=models.IntegerField(default=0),
        ),
    ]
