# Generated by Django 5.1.4 on 2025-01-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0016_book_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
    ]
