# Generated by Django 5.1.4 on 2025-01-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0017_alter_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_slug',
            field=models.SlugField(null=True),
        ),
    ]
