# Generated by Django 5.1.4 on 2025-01-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0018_book_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
