# Generated by Django 5.1.4 on 2025-01-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0019_alter_book_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='english_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان انگلیسی'),
        ),
    ]
