# Generated by Django 5.1.4 on 2025-01-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0021_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='english_title',
            field=models.CharField(max_length=100, verbose_name='عنوان انگلیسی'),
        ),
    ]
