# Generated by Django 5.1.4 on 2025-01-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0022_alter_book_english_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
