# Generated by Django 5.1.4 on 2025-01-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0024_category_english_name_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='english_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
