# Generated by Django 5.1.4 on 2025-01-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0026_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment_number',
            field=models.IntegerField(default=0),
        ),
    ]
