# Generated by Django 5.1.4 on 2025-01-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0029_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
