# Generated by Django 5.1.4 on 2025-01-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmanager', '0038_book_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='download_number',
            field=models.IntegerField(default=0),
        ),
    ]
