# Generated by Django 5.1.4 on 2025-01-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
