# Generated by Django 5.1.4 on 2025-01-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='assets/img/default-profile.webp', upload_to='profile_pics'),
        ),
    ]
