# Generated by Django 5.1.4 on 2025-01-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
